
backend:
  name: git-gateway
  branch: master

development_overrides:
  backend:
    name: file-system
    api_root: 'http://localhost:8000/api'

media_folder: static/img
public_folder: /img


collections:
  - label: "Blog"
    name: "mdx"
    folder: "content/posts"
    extension: mdx
    format: frontmatter
    widget: mdx
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "mdx"}